//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP323_Gusakov_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int MasterID { get; set; }
        public int ServiceID { get; set; }
        public string PaymentMethod { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
